apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss-army-knife
  labels:
    app: swiss-army-knife
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: swiss-army-knife
  template:
    metadata:
      labels:
        app: swiss-army-knife
    spec:
      containers:
      - name: swiss-army-knife
        image: "leodotcloud/swiss-army-knife:{{ .Values.image.version }}"
        ports:
        - containerPort: 8080