apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
  labels:
    app: netshoot
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: "nicolaka/netshoot:{{ .Values.image.version }}"
        ports:
        - containerPort: 8080